# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nuevo_producto.ui'
#
# Created: Thu Mar  1 16:17:28 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_dialogo_agregar_producto(object):
    def setupUi(self, dialogo_agregar_producto):
        dialogo_agregar_producto.setObjectName(_fromUtf8("dialogo_agregar_producto"))
        dialogo_agregar_producto.resize(584, 215)
        self.verticalLayout_4 = QtGui.QVBoxLayout(dialogo_agregar_producto)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(dialogo_agregar_producto)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(dialogo_agregar_producto)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.line_codigo = QtGui.QLineEdit(dialogo_agregar_producto)
        self.line_codigo.setMaxLength(60)
        self.line_codigo.setObjectName(_fromUtf8("line_codigo"))
        self.horizontalLayout.addWidget(self.line_codigo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(dialogo_agregar_producto)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.line_nombre = QtGui.QLineEdit(dialogo_agregar_producto)
        self.line_nombre.setMaxLength(100)
        self.line_nombre.setObjectName(_fromUtf8("line_nombre"))
        self.horizontalLayout_2.addWidget(self.line_nombre)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(dialogo_agregar_producto)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.line_descripcion = QtGui.QLineEdit(dialogo_agregar_producto)
        self.line_descripcion.setMaxLength(250)
        self.line_descripcion.setObjectName(_fromUtf8("line_descripcion"))
        self.horizontalLayout_3.addWidget(self.line_descripcion)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(dialogo_agregar_producto)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.dsb_precio = QtGui.QDoubleSpinBox(dialogo_agregar_producto)
        self.dsb_precio.setObjectName(_fromUtf8("dsb_precio"))
        self.horizontalLayout_4.addWidget(self.dsb_precio)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(dialogo_agregar_producto)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.sb_existencia = QtGui.QSpinBox(dialogo_agregar_producto)
        self.sb_existencia.setObjectName(_fromUtf8("sb_existencia"))
        self.horizontalLayout_5.addWidget(self.sb_existencia)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.pb_aceptar = QtGui.QPushButton(dialogo_agregar_producto)
        self.pb_aceptar.setObjectName(_fromUtf8("pb_aceptar"))
        self.horizontalLayout_7.addWidget(self.pb_aceptar)
        self.pb_cancelar = QtGui.QPushButton(dialogo_agregar_producto)
        self.pb_cancelar.setObjectName(_fromUtf8("pb_cancelar"))
        self.horizontalLayout_7.addWidget(self.pb_cancelar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(dialogo_agregar_producto)
        QtCore.QMetaObject.connectSlotsByName(dialogo_agregar_producto)

    def retranslateUi(self, dialogo_agregar_producto):
        dialogo_agregar_producto.setWindowTitle(QtGui.QApplication.translate("dialogo_agregar_producto", "Agregar Producto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("dialogo_agregar_producto", "Nuevo Producto", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("dialogo_agregar_producto", "Código", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("dialogo_agregar_producto", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("dialogo_agregar_producto", "Descripcion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("dialogo_agregar_producto", "Precio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("dialogo_agregar_producto", "Cantidad", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_aceptar.setText(QtGui.QApplication.translate("dialogo_agregar_producto", "Aceptar", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancelar.setText(QtGui.QApplication.translate("dialogo_agregar_producto", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))

